CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_user_email ON users(email);

CREATE TABLE IF NOT EXISTS keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    type VARCHAR(50) NOT NULL,
    algorithm VARCHAR(50) NOT NULL,
    key_data TEXT NOT NULL,
    public_key_data TEXT,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_key_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_key_user ON keys(user_id);
CREATE INDEX IF NOT EXISTS idx_key_type_algo ON keys(type, algorithm);

CREATE TABLE IF NOT EXISTS documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename VARCHAR(255) NOT NULL,
    path_enc VARCHAR(500) NOT NULL,
    iv VARCHAR(64) NOT NULL,
    tag VARCHAR(64) NOT NULL,
    wrapped_key TEXT NOT NULL,
    key_id BIGINT NOT NULL,
    file_hash VARCHAR(64),
    original_size BIGINT,
    content_type VARCHAR(100),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_doc_key FOREIGN KEY (key_id) REFERENCES keys(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_doc_key ON documents(key_id);
CREATE INDEX IF NOT EXISTS idx_doc_filename ON documents(filename);
